name: secrets

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: secret scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified
