name: secrets

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: secret scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified
